module.exports = {
  get: {
    PHONE_CLIENT: "PHONE_CLIENT",
    GAME_ROOM: "GAME_ROOM",
    PHONE_READY: "PHONE_READY",
    POSE_DETECTION: "POSE_DETECTION",
    CREATE_ROOM: "CREATE_ROOM",
    GAME_DONE: "GAME_DONE",
    GAME_STARTED: "GAME_STARTED",
  },
  response: {
    R_GAME_STARTED: "R_GAME_STARTED",
    R_ERROR: "R_ERROR",
    R_POSE_DETECTION: "R_POSE_DETECTION",
    R_PHONE_CLIENT: "R_PHONE_CLIENT",
    R_GAME_POSE: "R_GAME_POSE",
    R_GAME_ROOM: "R_GAME_ROOM",
    R_GAME_DONE: "R_GAME_DONE",
    R_READY: "R_READY",
    R_PHONE_CONNECTED: "R_PHONE_CONNECTED",
    R_ROOM_OCCUPIED: "R_ROOM_OCCUPIED",
  },
};
